# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Senior Software Engineer
email: N/A
description: > 
  Sarah is a Senior Software Engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pearljam66.github.io/sarah.github.io/"
github_username:  Pearljam66

# Build settings
markdown: kramdown
